name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    #uses: ./.github/workflows/maven.yml
    steps:
    - uses: actions/checkout@v3
    - name: Locate izinga order manager module docker file
      run:  cd ../../izinga-ordermanager
    - name: Build the Docker image
      run: docker build . --file ./izinga-ordermanager/Dockerfile --tag my-image-name:$(date +%s)
