name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    #uses: ./.github/workflows/maven.yml
    steps:
    - uses: actions/checkout@v3
    - name: Locate izinga order manager module docker file
      run:  cd ./izinga-ordermanager
    - name: Build the Docker image
      run: docker build -t ijudi-api .
    - name: Tag Docker image
      run: ijudi-api:latest 316005840972.dkr.ecr.af-south-1.amazonaws.com/ijudi-api:$(date +%s)
