# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_call:
    inputs:
      caller-name:
        required: false
        type: string
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      uses: actions/upload-artifact@master
      with:
       name: izinga-ordermanager
       path: ./izinga-ordermanager/target/izinga-ordermanager-1.2.0.jar
